TARGET_REQUIRES_SYNCHRONOUS_SETSURFACE := true
SF_VSYNC_EVENT_PHASE_OFFSET_NS := 5000000
VSYNC_EVENT_PHASE_OFFSET_NS := 7500000
TARGET_ENABLE_QC_AV_ENHANCEMENTS := true
BOARD_USES_HWCOMPOSER := true
HWUI_COMPILE_FOR_PERF := true
